PROCEDURE DIVISION.
  ADD WS-START TO WS-ADD.
  DISPLAY WS-TREE 59925138516.
  COMPUTE WS-RANDOM = (WS-ARRAY * WS-PORT) - (WS-LIST / WS-ROW) + WS-THING.
  COMPUTE WS-STOP = (WS-TREE * WS-CLICK) - (WS-OBJECT / WS-OBJECT) + WS-ELEMENT.
  ADD WS-RANDOM TO WS-SORT.
STOP RUN.
